### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by soumenms2015** [usnistgov/SCTK#10]
Hi,

Does it support windows??

Regards,
Soumen

**Comment by jfiscus** [comment]
Not directly but we have compiled it using cygwin to install a unix environment.

**Comment by soumenms2015** [comment]
how can I  do that? Could you please explain in detail? I am using windows2012

**Comment by jfiscus** [comment]
1. Install cygwin -  https://www.cygwin.com/. You'll need c, c++, perl, bash 
2. Start a cygwin bash shell window
3. Follow the UNIX install instructions.  Note, the code will only be runable in a cygwin environment and not under Windows such as a console

**Comment by soumenms2015** [comment]
does this tool only support Cygwin | 1.3 - 2.0B2,  not Cygwin64 ?

**Comment by jfiscus** [comment]
Likely both

**Comment by soumenms2015** [comment]
So in order to install make config and corresponding command , do I need to install all four compilers c, c++, perl and bash?

**Comment by jfiscus** [comment]
yes. you'll need them.  This is a UNIX-based software package that works on the commandline.  you will essentially be installing a stripped down UNIX environment.  You can always dual boot to Linux.

**Comment by soumenms2015** [comment]
Hello,

After successfully run the commands make config and make all, I got the below error while running the command make check.

N.B: csrfilt.sh testing was successful.

(cd hubscr && make check)
make[2]: Entering directory '/cygdrive/c/Users/Admin/Downloads/SCTK-master/SCTK-master/src/hubscr'
Testing hubscr.pl
./RunTests.pl
   Running test 'test1-sastt', operation 'test', options '-G -f rttm -F rttm -a', directory 'test1-sastt.test'
      Executing command
      Comparing output
[ERROR] Test test1-sastt has failed.  Diff output is :
Only in test1-sastt.test/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d*_NONE_1.html


make[2]: *** [makefile:20: check] Error 1
make[2]: Leaving directory '/cygdrive/c/Users/Admin/Downloads/SCTK-master/SCTK-master/src/hubscr'
make[1]: *** [makefile:95: checkFast] Error 2
make[1]: Leaving directory '/cygdrive/c/Users/Admin/Downloads/SCTK-master/SCTK-master/src'
make: *** [makefile:52: check] Error 2

Does this error effect the running of following commands or complete installation?

**Comment by soumenms2015** [comment]
If I consider this successful installation, can you please let me know how I can use it for WER and Weighted Word Error Rate by using hypothesis and reference text?

**Comment by jfiscus** [comment]
Text file scoring is no longer supported.  You need to use a format called 'trn' which is defined in doc/infmts.htm accesible through doc/sclite.htm.  For additional examples, run the script src/sclite/testdata/tsclite.sh and look through the examples.  Test1 uses the trn format.

**Comment by pengzhendong** [comment]
Why use * in file name?
https://github.com/usnistgov/SCTK/blob/master/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments/ICSI_20011030-1030_d*_NONE_1.html
I can not clone it in windows.

**Comment by pengzhendong** [comment]
Why use * in file name? @jfiscus 
https://github.com/usnistgov/SCTK/blob/master/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments/ICSI_20011030-1030_d*_NONE_1.html
I can not clone it in windows.

**Comment by YimengZhu** [comment]
Any updates on this issue? I notice there are some windows header files included in the code. Do you have direct windows support now?

BTW, the * on the file path make it unable to checkout the repo on windows.

**Comment by jfiscus** [comment]
I removed the asterisk from the filename and I will close this issue.
