### ISSUE TITLE
make all gives error

### ISSUE THREAD

**Issue by soumenms2015** [usnistgov/SCTK#11]
(mkdir -p bin)
(cd src && if test -f makefile ; then make all ; fi)
make[1]: Entering directory '/.../.../SCTK/src'
(cd asclite && if test -f makefile ; then make all ; fi)
make[2]: Entering directory '/.../.../SCTK/src/asclite'
(cd core && if test -f makefile ; then make all ; fi)
make[3]: Entering directory '/.../.../SCTK/src/asclite/core'
g++ -c  -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DHAVE_LIBM=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STRING_H=1 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MATH_H=1 -DHAVE_TIME_H=1 -DHAVE_ASSERT_H=1 -DHAVE_FLOAT_H=1 -DHAVE_LIMITS_H=1  -I. -g -Os  -g -Os recording.cpp
In file included from /usr/include/c++/5/array:35:0,
                 from sgml_reportgenerator.h:29,
                 from recording.h:35,
                 from recording.cpp:24:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
makefile:60: recipe for target 'recording.o' failed
make[3]: *** [recording.o] Error 1
make[3]: Leaving directory '/.../.../SCTK/src/asclite/core'
makefile:12: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/.../.../SCTK/src/asclite'
makefile:12: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/.../.../SCTK/src'
makefile:19: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jfainberg** [comment]
Set CXXFLAGS to `-std=c++11`:
`export CXXFLAGS="-std=c++11" && make config`
This will add "-std=c++11" as a flag to g++ in src/asclite/core/makefile when running `make config`.

**Comment by sishtiaq** [comment]
Can this flag not be made the default? I've just hit this, a year later .

**Comment by jfiscus** [comment]
I just accepted https://github.com/usnistgov/SCTK/pull/33 that should fix this problem.
