### ISSUE TITLE
Not Enough Reference files loaded

### ISSUE THREAD

**Issue by LingweiKong** [usnistgov/SCTK#15]
I compared the original txt with the labeled txt file as usual to test ASR accuracy, however this time I met the error of `Not Enough Reference files loaded`, and my comand is `sclite -h *.txt -r **.txt -i wsj -e gb -c NOASCII -o all`

**Comment by jfiscus** [comment]
There are a couple problems with your command.  Sclite will only accept one file for -h and -r.  You are using the same files for the hyp and ref.  I'd have to see the files to give further help.

**Comment by LingweiKong** [comment]
> There are a couple problems with your command. Sclite will only accept one file for -h and -r. You are using the same files for the hyp and ref. I'd have to see the files to give further help.

I‘m sorry I was using SCilte not SCTK, comparing reference to Hypothesis. This error happens when one of the record in reference file missed the title content. I have solved the problem, and thanks a lot.

**Comment by jawaharvignesh** [comment]
> > There are a couple problems with your command. Sclite will only accept one file for -h and -r. You are using the same files for the hyp and ref. I'd have to see the files to give further help.
> 
> I‘m sorry I was using SCilte not SCTK, comparing reference to Hypothesis. This error happens when one of the record in reference file missed the title content. I have solved the problem, and thanks a lot.

Hi @drkingman , I know this is an old and closed thread. But I am getting the same error, and this is the only reference to this error I could find. I don't understand  what `missed the title content` means. Could you please explain how you solved this error?

**Comment by LingweiKong** [comment]
> > > There are a couple problems with your command. Sclite will only accept one file for -h and -r. You are using the same files for the hyp and ref. I'd have to see the files to give further help.
> > 
> > 
> > I‘m sorry I was using SCilte not SCTK, comparing reference to Hypothesis. This error happens when one of the record in reference file missed the title content. I have solved the problem, and thanks a lot.
> 
> Hi @drkingman , I know this is an old and closed thread. But I am getting the same error, and this is the only reference to this error I could find. I don't understand what `missed the title content` means. Could you please explain how you solved this error?

@jawaharvignesh You have to list every recording's  name after the txt content. like
xxxxxxxxxxx (1.txt)
xxxxxxxxxxx (2.txt)
......

**Comment by Duzij** [comment]
@LingweiKong could you please provide a sample command? Could you elaborate what recordings are you referring to? 
In my txt files there are no references, but rather just text, that I'm trying to compare line by line.
Thanks!

**Comment by jfiscus** [comment]
Do a git pull and look at the demo in doc/sctk.htm.

**Comment by Duzij** [comment]
Thank you! It actually helped a lot. 
Also, I figured that I need to add additional line break at the end of both reference and hypothesis files.
Without this, only one line with version is returned:
`sclite: 2.10 TK Version 1.3`
 It that intentional?

**Comment by jfiscus** [comment]
Glad to hear it helped.  The files are expected to be in UNIX text file format (using \n to separate lines, even the last line.)  I'm not sure I can re-create that test.  Unfortunately file validation could be improved in the package)

**Comment by lececefifi** [comment]
Hello - I am getting the same error - I am comparing ref of .stm and hyp of .ctm using word timestamp, :  -s -i rm -r 1a.stm -h 1ax.ctm -o all

(had to change the file ext to .txt in order to upload)

Here's my errors:
_Error: double reference text for id ''
_Error: Not enough Reference files loaded_
_Missing:__

Perhaps there are issues with my command line prompt, or installation of sclite? Because .txt files would provide output, .but not for stm and .ctm files (even with testdata files from SCTK/src/sclite'/testdata (lvc_hyp.ctm, lvc_ref.stm).

Thank you in advance for the help!

[1a.txt](https://github.com/user-attachments/files/18689194/1a.txt)
[1ax.txt](https://github.com/user-attachments/files/18689195/1ax.txt)
