### ISSUE TITLE
Word-weight-list file

### ISSUE THREAD

**Issue by chuckcho** [usnistgov/SCTK#16]
As per https://github.com/usnistgov/SCTK/blob/master/doc/sclite.htm#L260-L265, one can supply a `word-weight-list file` that lists weights for words. If there's a "standard" or any example word-weight-list file that I can try, where can I download?

**Comment by jfiscus** [comment]
The Test1C test in sclite shows an example of the call to sclite 'https://github.com/usnistgov/SCTK/blob/master/src/sclite
/testdata/base/test1c.com' and refers to a sample 'https://github.com/usnistgov/SCTK/blob/master/src/sclite/testdata/csrnab_r.wwl'.
