### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by frankhetao** [usnistgov/SCTK#17]
the error cmd info below，tks

> jg.setColor("DimGray");
 > jg.setStroke(2);
 > jg.drawLine(670*scale, 75, 800*scale, 75);
 > jg.setFont("arial","11px",Font.PLAIN);
 > jg.drawStringRect("T", 670*scale + 1, 58, 130*scale - 1, "center");
 > jg.drawImage("images/white_dk.gif", 670*scale - 7, 75 - 7, 14, 14);
 > jg.drawImage("images/white_dk.gif", 800*scale - 7, 75 - 7, 14, 14);

makefile:19: recipe for target 'check' failed
make[2]: *** [check] Error 1
make[2]: Leaving directory '/root/Desktop/kaldi/tools/sctk-2.4.10/src/hubscr'
makefile:62: recipe for target 'checkFast' failed
make[1]: *** [checkFast] Error 2
make[1]: Leaving directory '/root/Desktop/kaldi/tools/sctk-2.4.10/src'
makefile:51: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by ugrozkr** [comment]
I was get same error too. I think that this errror getten by sctk toolkit packages. I try to install on ubuntu 14.x version and this step successfully passed. It this version based compilation problem. Can anyone have any idea about this problem ?

**Comment by jfiscus** [comment]
I just tested on Ubuntu 18.04 and the issue is not present.
