### ISSUE TITLE
Remove * from filename

### ISSUE THREAD

**Issue by xkszltl** [usnistgov/SCTK#18]
There's a `*` in filename...
Because of this, the repo cannot be cloned correctly on Windows.

https://github.com/usnistgov/SCTK/blob/master/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments/ICSI_20011030-1030_d*_NONE_1.html

We can certainly ignore that file since it's not used by us.
However, if we use this repo as a git submodule with a CI system, there's no way around to ignore an error at repo checkout stage (in case if you're not familiar with test, CI system does automatic build/test and source code checkout is usually treated specially and not customizable to ignore error)

```
PS D:\> git clone https://github.com/usnistgov/SCTK
Cloning into 'SCTK'...
remote: Enumerating objects: 5115, done.
remote: Total 5115 (delta 0), reused 0 (delta 0), pack-reused 5115R
Receiving objects: 100% (5115/5115), 7.25 MiB | 10.69 MiB/s, done.
Resolving deltas: 100% (3661/3661), done.
error: unable to create file src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments/ICSI_20011030-1030_d*_NONE_1.html: Invalid argument
Checking out files: 100% (1415/1415), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by jfiscus** [comment]
Resolved with today's update.
