### ISSUE TITLE
No any response when i run rover

### ISSUE THREAD

**Issue by QuadraV-Speech** [usnistgov/SCTK#22]
after compiling sctk successfully , i got no response when i input
"rover -h 1.ctm -h 2.ctm -o result.ctm -m maxconfa"

**Comment by ysinha94** [comment]
Hi, did you find out where the output file is located?

**Comment by abnerLing** [comment]
I'm getting the same issue :(

**Comment by jfiscus** [comment]
In the src/sclite/testdata dir, run: 
../rover -h lvc_hypc.ctm ctm -h lvc_hypr.ctm ctm -o foo.ctm -m maxconf


Input Options:
    -h hypfile ctm
                Define the hypothesis file **and** it's format. This option
                must be used more than once.

**Comment by abnerLing** [comment]
Thank you very much! Initially, I didn't include the format of the hypothesis file. Everything is working fine now.
