### ISSUE TITLE
sclite compilation failed 

### ISSUE THREAD

**Issue by ugrozkr** [usnistgov/SCTK#23]
I try to compile 2.4.10 version of sctk on ubuntu 18 operating system. When make config part finished and make second part started then terminal shows following error:

make[2]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
make[1]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10'
touch sctk/.configured
cd sctk; \
make CC="cc" CXX="g++" all && make install && make doc
make[1]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10'
(mkdir -p bin)
(cd src; make all)
make[2]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
(cd asclite; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd core; make all)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
(cd test; make all)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd sclite; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
(cd rfilter1; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rfilter1'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rfilter1'
(cd csrfilt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/csrfilt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/csrfilt'
(cd chfilt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/chfilt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/chfilt'
(cd hamzaNorm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hamzaNorm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hamzaNorm'
(cd tanweenFilt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/tanweenFilt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/tanweenFilt'
(cd acomp; make all)	
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/acomp'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/acomp'
(cd def_art; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/def_art'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/def_art'
(cd hubscr; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hubscr'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hubscr'
(cd utf_filt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/utf_filt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/utf_filt'
(cd rttmSort; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSort'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSort'
(cd rttm2ctm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttm2ctm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttm2ctm'
(cd rttmSmooth; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSmooth'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSmooth'
(cd spkr2sad; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/spkr2sad'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/spkr2sad'
(cd mergectm2rttm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/mergectm2rttm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/mergectm2rttm'
(cd align2html; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/align2html'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/align2html'
(cd md-eval; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/md-eval'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/md-eval'
(cd stm2rttm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stm2rttm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stm2rttm'
(cd stmValidator; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stmValidator'
perl buildInstallVersion.pl > stmValidator.pl
chmod +x stmValidator.pl
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stmValidator'
(cd rttmValidator; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmValidator'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmValidator'
(cd ctmValidator; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/ctmValidator'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/ctmValidator'
(cd slatreport; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/slatreport'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/slatreport'
make[2]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
make[1]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10'
make[1]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10'
(mkdir -p bin)
(cd src; make install)
make[2]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
(cd asclite; make install)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd core; make install)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
for p in asclite; do \
	/usr/bin/install $p /home/ugur/kaldi/tools/sctk/bin/$p; \
done
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
(cd test; make install)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[4]: Nothing to be done for 'install'.
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd sclite; make install)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
/bin/sh: 5: Syntax error: end of file unexpected (expecting "done")
makefile:171: recipe for target 'testinstalldirs' failed
make[3]: [testinstalldirs] Error 2 (ignored)
for p in sclite sc_stats rover sctkUnit; do \
  /usr/bin/install $p -prefi/home/ugur/kaldi/tools/sctk/bin/$p; \
done
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
makefile:160: recipe for target 'install' failed
make[3]: *** [install] Error 1
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
makefile:12: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
makefile:19: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10'
Makefile:108: recipe for target 'sclite_compiled' failed
make: *** [sclite_compiled] Error 2

**Comment by ryandesign** [comment]
There were many fixes in 2.4.12 which was just released. Try again with that version?

**Comment by jfiscus** [comment]
I'm going to close this issue as @ryandesign noted the fixes 11/7/21.
