### ISSUE TITLE
md-eval.pl tests don't work under perl >=  5.26

### ISSUE THREAD

**Issue by jtrmal** [usnistgov/SCTK#3]
Hi, one of our (Kaldi) contributors has found and reported sctk issue for  perl 
See here: https://github.com/kaldi-asr/kaldi/pull/2246

I looked at the code and it seems there is actually a bug in the code (src/md-eval/md-eval.pl):
instead of 
```
1099     $word->{WORD} =~ lc $word->{WORD}; #lower case
```
I believe it should say
```
1099     $word->{WORD} = lc $word->{WORD}; #lower case
```
Do you want me to create PR or are you fixing it by yourselves?

**Comment by jfiscus** [comment]
Jan,

I found that one too … after staring at if for a loooooong time.  Please make a PR.  That’ll help a lot.

-Jon

**Comment by jfiscus** [comment]
This was corrected by jtrmal-sctk_fix merge request.
