### ISSUE TITLE
Build Failed on macOS, Error while running command "make all".

### ISSUE THREAD

**Issue by H-111-di** [usnistgov/SCTK#36]
Full make output is in the attachment: [make_all.log](https://github.com/usnistgov/SCTK/files/8055698/make_all.log).

macOS version: 12.2.1
gcc/g++/clang version: Apple clang version 13.0.0 (clang-1300.0.27.3)

There are two things I noticed in the warning and error.
1. There're warnings from `ld` command like:
    ```bash
    ld: warning: object file (alignedsegmentiterator.o) was built for newer macOS version (12.2) than being linked (12.0)
    ```
2. Errors like:
    ```bash
    Undefined symbols for architecture x86_64:
    "std::__basic_file<char>::is_open() const", referenced from:
        CTMInputParser::loadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in ctm_inputparser.o
        RAWSYSReportGenerator::Generate(Alignment*, int) in rawsys_reportgenerator.o
        RTTMInputParser::loadFileLexeme(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in rttm_inputparser.o
        RTTMInputParser::loadFileSpeaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in rttm_inputparser.o
        SGMLGenericReportGenerator::Generate(int) in sgml_generic_reportgenerator.o
        SGMLReportGenerator::Generate(Alignment*, int) in sgml_reportgenerator.o
        SpeakerMatch::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in speakermatch.o
        ...
    ```

And I will have `ld: symbol(s) not found for architecture x86_64` in the ending.

This is quite wired since I can get the same compiling work done on My M1 MacBook Air with the same system version(different clang version though, MBA's clang is -1300.0.29.30) as long as I change the parameter in Kaldi's makefile following  [this issue](https://github.com/kaldi-asr/kaldi/issues/4418) in Kaldi's repo. And since the `-march=native` parameter works fine on x64, it should be fine with no need to modify that.

Then I tried using the lasted repo clone(2.4.12, different from the 2.4.11 from Kaldi's tools directory). Same issues still.

**Comment by jfiscus** [comment]
@H-111-di Please re-clone the repo and try again.  There have been many updates recently.
