### ISSUE TITLE
Update LICENSE.md to reference "software" instead of "data"?

### ISSUE THREAD

**Issue by arlofaria** [usnistgov/SCTK#39]
The current `LICENSE.md` (added in 2016) references the word "data" 15 times and "software" 0 times.

At the bottom of the file it links to an "online version" at http://www.nist.gov/open/license.cfm ... which today (in 2022) redirects to https://www.nist.gov/open/copyright-fair-use-and-licensing-statements-srd-data-software-and-technical-series-publications

That page seems to indicate more information distinguishing among SRD data, non-SRD data/works, and "NIST software".  It seems like that last category is perhaps most appropriate for SCTK.  In particular, it says:

>  Distributions of NIST created software, whether in source or compiled form, should include the following licensing statement:

> NIST-developed software is provided by NIST as a public service. You may use, copy, and distribute copies of the software in any medium, provided that you keep intact this entire notice. You may improve, modify, and create derivative works of the software or any portion of the software, and you may copy and distribute such modifications or works. Modified works should carry a notice stating that you changed the software and should note the date and nature of any such change. Please explicitly acknowledge the National Institute of Standards and Technology as the source of the software. 
>
> NIST-developed software is expressly provided "AS IS." NIST MAKES NO WARRANTY OF ANY KIND, EXPRESS, IMPLIED, IN FACT, OR ARISING BY OPERATION OF LAW, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND DATA ACCURACY. NIST NEITHER REPRESENTS NOR WARRANTS THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED. NIST DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF THE SOFTWARE OR THE RESULTS THEREOF, INCLUDING BUT NOT LIMITED TO THE CORRECTNESS, ACCURACY, RELIABILITY, OR USEFULNESS OF THE SOFTWARE.
>
> You are solely responsible for determining the appropriateness of using and distributing the software and you assume all risks associated with its use, including but not limited to the risks and costs of program errors, compliance with applicable laws, damage to or loss of data, programs or equipment, and the unavailability or interruption of operation. This software is not intended to be used in any situation where a failure could cause risk of injury or damage to property. The software developed by NIST employees is not subject to copyright protection within the United States.

Note that the text above mentions "data" twice (w.r.t. accuracy and loss) and mentions "software" 13 times.

Would it be more appropriate to update SCTK's `LICENSE.md` to match what's at the linked nist.gov webpage?

(For context, I'm not a lawyer, but I'd like to show the SCTK license to some lawyers and pre-empt their concerns.)

**Comment by jfiscus** [comment]
Updated to the contemporary text with https://github.com/usnistgov/SCTK/commit/862526abdf247bebee7c8e9784f7c482b005af27.  Thanks @arlofaria !

**Comment by arlofaria** [comment]
Thanks!  This will make it easier for the lawyers. 😄
