### ISSUE TITLE
Requesting for complete instructions along with command line arguments(with one exmple) for operating rover v0.1

### ISSUE THREAD

**Issue by mukherjeesougata-eros** [usnistgov/SCTK#41]
I tried to compile SCTK/sclite/rover.c with the command gc rover.c -o rover . But it gave me the following error:-
```
/usr/bin/ld: /tmp/cc91UyS4.o: in function `mfalign_ctm_files_v1':
rover.c:(.text+0x207): undefined reference to `mfdb'
/usr/bin/ld: rover.c:(.text+0x645): undefined reference to `new_WORD'
/usr/bin/ld: rover.c:(.text+0x72e): undefined reference to `WTOKE_STR1_init'
/usr/bin/ld: rover.c:(.text+0x798): undefined reference to `locate_next_file_channel'
/usr/bin/ld: rover.c:(.text+0x814): undefined reference to `mfdb'
/usr/bin/ld: rover.c:(.text+0xa9b): undefined reference to `Network_traverse'
/usr/bin/ld: rover.c:(.text+0xaa7): undefined reference to `Network_destroy'
/usr/bin/ld: rover.c:(.text+0xbe6): undefined reference to `find_common_silence'
/usr/bin/ld: rover.c:(.text+0xc75): undefined reference to `free_mark_file'
/usr/bin/ld: rover.c:(.text+0xcbb): undefined reference to `release_WORD'
/usr/bin/ld: rover.c:(.text+0xcf4): undefined reference to `cleanup_NET_ALIGN'
/usr/bin/ld: /tmp/cc91UyS4.o: in function `print_linear':
rover.c:(.text+0x17d9): undefined reference to `mfdb'
/usr/bin/ld: rover.c:(.text+0x1caf): undefined reference to `mfdb'
/usr/bin/ld: rover.c:(.text+0x1e73): undefined reference to `mfdb'
/usr/bin/ld: rover.c:(.text+0x1ff2): undefined reference to `glob_ties'
/usr/bin/ld: rover.c:(.text+0x1ffb): undefined reference to `glob_ties'
/usr/bin/ld: rover.c:(.text+0x2034): undefined reference to `mfdb'
/usr/bin/ld: /tmp/cc91UyS4.o: in function `perform_mfalign_v1':
rover.c:(.text+0x2720): undefined reference to `new_WORD'
/usr/bin/ld: rover.c:(.text+0x2746): undefined reference to `rsprintf'
/usr/bin/ld: rover.c:(.text+0x27b3): undefined reference to `use_count_WORD'
/usr/bin/ld: rover.c:(.text+0x27bb): undefined reference to `make_empty_WORD'
/usr/bin/ld: rover.c:(.text+0x27c3): undefined reference to `copy_WORD'
/usr/bin/ld: rover.c:(.text+0x27cb): undefined reference to `opt_del_WORD'
/usr/bin/ld: rover.c:(.text+0x27d3): undefined reference to `null_alt_WORD'
/usr/bin/ld: rover.c:(.text+0x27db): undefined reference to `release_WORD'
/usr/bin/ld: rover.c:(.text+0x27e3): undefined reference to `equal_WORD2'
/usr/bin/ld: rover.c:(.text+0x27ed): undefined reference to `print_WORD_wt'
/usr/bin/ld: rover.c:(.text+0x27fb): undefined reference to `Network_create_from_WTOKE'
/usr/bin/ld: rover.c:(.text+0x2887): undefined reference to `Network_traverse'
/usr/bin/ld: rover.c:(.text+0x28a4): undefined reference to `wwd_WORD_rover'
/usr/bin/ld: rover.c:(.text+0x28b0): undefined reference to `wwd_time_WORD'
/usr/bin/ld: rover.c:(.text+0x28d3): undefined reference to `Network_dpalign_n_networks'
/usr/bin/ld: rover.c:(.text+0x28fb): undefined reference to `Network_destroy'
/usr/bin/ld: rover.c:(.text+0x2927): undefined reference to `release_WORD'
/usr/bin/ld: /tmp/cc91UyS4.o: in function `set_tag1':
rover.c:(.text+0x2976): undefined reference to `set_WORD_tag1'
collect2: error: ld returned 1 exit status
```

@jfiscus kindly  please give me the complete instructions along with command line arguments (with one example) for operating rover v0.1
OS - Ubuntu 20.04
compiler- gcc

**Comment by jfiscus** [comment]
Hi,

After you get the packaged compiled. I made a rover demo script and just pushed it to the repo.  Do a git pull and see doc/rover.htm for information.

Best regards,
Jon

From: Fiscus, Jonathan G. (Fed) ***@***.***>
Date: Thursday, September 8, 2022 at 7:05 AM
To: usnistgov/SCTK ***@***.***>, usnistgov/SCTK ***@***.***>
Cc: Mention ***@***.***>, Fiscus, Jonathan G. (Fed) ***@***.***>
Subject: Re: [usnistgov/SCTK] Requesting for complete instructions along with command line arguments(with one exmple) for operating rover v0.1 (Issue #41)
Hi,

Did you clone the repo?  Please send the log of all these commands when you execute them from the top level of the repo:

        % make config
        % make all
        % make check
        % make install
        % make doc

Thanks,
Jon

From: mukherjeesougata ***@***.***>
Date: Thursday, September 8, 2022 at 7:01 AM
To: usnistgov/SCTK ***@***.***>
Cc: Fiscus, Jonathan G. (Fed) ***@***.***>, Mention ***@***.***>
Subject: [usnistgov/SCTK] Requesting for complete instructions along with command line arguments(with one exmple) for operating rover v0.1 (Issue #41)

I tried to compile SCTK/sclite/rover.c with the command gc rover.c -o rover . But it gave me the following error:-

/usr/bin/ld: /tmp/cc91UyS4.o: in function `mfalign_ctm_files_v1':

rover.c:(.text+0x207): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x645): undefined reference to `new_WORD'

/usr/bin/ld: rover.c:(.text+0x72e): undefined reference to `WTOKE_STR1_init'

/usr/bin/ld: rover.c:(.text+0x798): undefined reference to `locate_next_file_channel'

/usr/bin/ld: rover.c:(.text+0x814): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0xa9b): undefined reference to `Network_traverse'

/usr/bin/ld: rover.c:(.text+0xaa7): undefined reference to `Network_destroy'

/usr/bin/ld: rover.c:(.text+0xbe6): undefined reference to `find_common_silence'

/usr/bin/ld: rover.c:(.text+0xc75): undefined reference to `free_mark_file'

/usr/bin/ld: rover.c:(.text+0xcbb): undefined reference to `release_WORD'

/usr/bin/ld: rover.c:(.text+0xcf4): undefined reference to `cleanup_NET_ALIGN'

/usr/bin/ld: /tmp/cc91UyS4.o: in function `print_linear':

rover.c:(.text+0x17d9): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x1caf): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x1e73): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x1ff2): undefined reference to `glob_ties'

/usr/bin/ld: rover.c:(.text+0x1ffb): undefined reference to `glob_ties'

/usr/bin/ld: rover.c:(.text+0x2034): undefined reference to `mfdb'

/usr/bin/ld: /tmp/cc91UyS4.o: in function `perform_mfalign_v1':

rover.c:(.text+0x2720): undefined reference to `new_WORD'

/usr/bin/ld: rover.c:(.text+0x2746): undefined reference to `rsprintf'

/usr/bin/ld: rover.c:(.text+0x27b3): undefined reference to `use_count_WORD'

/usr/bin/ld: rover.c:(.text+0x27bb): undefined reference to `make_empty_WORD'

/usr/bin/ld: rover.c:(.text+0x27c3): undefined reference to `copy_WORD'

/usr/bin/ld: rover.c:(.text+0x27cb): undefined reference to `opt_del_WORD'

/usr/bin/ld: rover.c:(.text+0x27d3): undefined reference to `null_alt_WORD'

/usr/bin/ld: rover.c:(.text+0x27db): undefined reference to `release_WORD'

/usr/bin/ld: rover.c:(.text+0x27e3): undefined reference to `equal_WORD2'

/usr/bin/ld: rover.c:(.text+0x27ed): undefined reference to `print_WORD_wt'

/usr/bin/ld: rover.c:(.text+0x27fb): undefined reference to `Network_create_from_WTOKE'

/usr/bin/ld: rover.c:(.text+0x2887): undefined reference to `Network_traverse'

/usr/bin/ld: rover.c:(.text+0x28a4): undefined reference to `wwd_WORD_rover'

/usr/bin/ld: rover.c:(.text+0x28b0): undefined reference to `wwd_time_WORD'

/usr/bin/ld: rover.c:(.text+0x28d3): undefined reference to `Network_dpalign_n_networks'

/usr/bin/ld: rover.c:(.text+0x28fb): undefined reference to `Network_destroy'

/usr/bin/ld: rover.c:(.text+0x2927): undefined reference to `release_WORD'

/usr/bin/ld: /tmp/cc91UyS4.o: in function `set_tag1':

rover.c:(.text+0x2976): undefined reference to `set_WORD_tag1'

collect2: error: ld returned 1 exit status

@jfiscus<https://github.com/jfiscus> kindly please give me the complete instructions along with command line arguments (with one example) for operating rover v0.1
OS - Ubuntu 20.04
compiler- gcc

**Comment by mukherjeesougata-eros** [comment]
Yes sir I  have cloned the repo . You can find the log file in the following link:- https://drive.google.com/file/d/1XrLYS4SedeFPmZdQHDte0F-JIGh5MgaB/view?usp=sharing

**Comment by jfiscus** [comment]
The screen log showed some compiler warnings but rover compiled and an executable should be in ./bin.  Can you execute this command:

./bin/rover

Or

./bin/sclite

-Jon

From: mukherjeesougata ***@***.***>
Date: Friday, September 9, 2022 at 12:43 AM
To: usnistgov/SCTK ***@***.***>
Cc: Fiscus, Jonathan G. (Fed) ***@***.***>, Mention ***@***.***>
Subject: Re: [usnistgov/SCTK] Requesting for complete instructions along with command line arguments(with one exmple) for operating rover v0.1 (Issue #41)

Yes sir I have cloned the repo . You can find the log file in the following link:- https://drive.google.com/file/d/1XrLYS4SedeFPmZdQHDte0F-JIGh5MgaB/view?usp=sharing<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1XrLYS4SedeFPmZdQHDte0F-JIGh5MgaB%2Fview%3Fusp%3Dsharing&data=05%7C01%7Cjonathan.fiscus%40nist.gov%7C6894d035eac740e9513d08da921dd216%7C2ab5d82fd8fa4797a93e054655c61dec%7C1%7C0%7C637982954025214871%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hwh3tN7dbX%2BHE4QLc7PI5eCYdEKI5j%2BLD0JNXdQoeVg%3D&reserved=0>

**Comment by mukherjeesougata-eros** [comment]
ya sir I have executed thoso commands, it is asking for arguments.So,I shall execute those commands along with the arguments.Right sir?

**Comment by jfiscus** [comment]
Yes, that is correct.

To respond to your stm/ctm question.  The purpose of the SCTK package is to evaluate the performance of automatic speech recognition systems using a data set of audio files.  The Linguistic Data Consortium has a vast repository of test collections and our latest ASR evaluations can be found at https://www.nist.gov/itl/iad/mig/openasr21-challenge-results.  The STM file is the reference transcript for the test material and the CTM is the system output of an ASR system.  The STM is a derived from manual transcription of the audio files and takes a lot of time to produce them.  I’d recommend getting one of the reference data sets from our evaluations.

I hope this helps.

Best regards,
Jon

From: mukherjeesougata ***@***.***>
Date: Saturday, September 10, 2022 at 3:26 AM
To: usnistgov/SCTK ***@***.***>
Cc: Fiscus, Jonathan G. (Fed) ***@***.***>, Mention ***@***.***>
Subject: Re: [usnistgov/SCTK] Requesting for complete instructions along with command line arguments(with one exmple) for operating rover v0.1 (Issue #41)

ya sir I have executed thoso commands, it is asking for arguments.So,I shall execute those commands along with the arguments.Right sir?

**Comment by jfiscus** [comment]
Hi,

Did you clone the repo?  Please send the log of all these commands when you execute them from the top level of the repo:

        % make config
        % make all
        % make check
        % make install
        % make doc

Thanks,
Jon

From: mukherjeesougata ***@***.***>
Date: Thursday, September 8, 2022 at 7:01 AM
To: usnistgov/SCTK ***@***.***>
Cc: Fiscus, Jonathan G. (Fed) ***@***.***>, Mention ***@***.***>
Subject: [usnistgov/SCTK] Requesting for complete instructions along with command line arguments(with one exmple) for operating rover v0.1 (Issue #41)

I tried to compile SCTK/sclite/rover.c with the command gc rover.c -o rover . But it gave me the following error:-

/usr/bin/ld: /tmp/cc91UyS4.o: in function `mfalign_ctm_files_v1':

rover.c:(.text+0x207): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x645): undefined reference to `new_WORD'

/usr/bin/ld: rover.c:(.text+0x72e): undefined reference to `WTOKE_STR1_init'

/usr/bin/ld: rover.c:(.text+0x798): undefined reference to `locate_next_file_channel'

/usr/bin/ld: rover.c:(.text+0x814): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0xa9b): undefined reference to `Network_traverse'

/usr/bin/ld: rover.c:(.text+0xaa7): undefined reference to `Network_destroy'

/usr/bin/ld: rover.c:(.text+0xbe6): undefined reference to `find_common_silence'

/usr/bin/ld: rover.c:(.text+0xc75): undefined reference to `free_mark_file'

/usr/bin/ld: rover.c:(.text+0xcbb): undefined reference to `release_WORD'

/usr/bin/ld: rover.c:(.text+0xcf4): undefined reference to `cleanup_NET_ALIGN'

/usr/bin/ld: /tmp/cc91UyS4.o: in function `print_linear':

rover.c:(.text+0x17d9): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x1caf): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x1e73): undefined reference to `mfdb'

/usr/bin/ld: rover.c:(.text+0x1ff2): undefined reference to `glob_ties'

/usr/bin/ld: rover.c:(.text+0x1ffb): undefined reference to `glob_ties'

/usr/bin/ld: rover.c:(.text+0x2034): undefined reference to `mfdb'

/usr/bin/ld: /tmp/cc91UyS4.o: in function `perform_mfalign_v1':

rover.c:(.text+0x2720): undefined reference to `new_WORD'

/usr/bin/ld: rover.c:(.text+0x2746): undefined reference to `rsprintf'

/usr/bin/ld: rover.c:(.text+0x27b3): undefined reference to `use_count_WORD'

/usr/bin/ld: rover.c:(.text+0x27bb): undefined reference to `make_empty_WORD'

/usr/bin/ld: rover.c:(.text+0x27c3): undefined reference to `copy_WORD'

/usr/bin/ld: rover.c:(.text+0x27cb): undefined reference to `opt_del_WORD'

/usr/bin/ld: rover.c:(.text+0x27d3): undefined reference to `null_alt_WORD'

/usr/bin/ld: rover.c:(.text+0x27db): undefined reference to `release_WORD'

/usr/bin/ld: rover.c:(.text+0x27e3): undefined reference to `equal_WORD2'

/usr/bin/ld: rover.c:(.text+0x27ed): undefined reference to `print_WORD_wt'

/usr/bin/ld: rover.c:(.text+0x27fb): undefined reference to `Network_create_from_WTOKE'

/usr/bin/ld: rover.c:(.text+0x2887): undefined reference to `Network_traverse'

/usr/bin/ld: rover.c:(.text+0x28a4): undefined reference to `wwd_WORD_rover'

/usr/bin/ld: rover.c:(.text+0x28b0): undefined reference to `wwd_time_WORD'

/usr/bin/ld: rover.c:(.text+0x28d3): undefined reference to `Network_dpalign_n_networks'

/usr/bin/ld: rover.c:(.text+0x28fb): undefined reference to `Network_destroy'

/usr/bin/ld: rover.c:(.text+0x2927): undefined reference to `release_WORD'

/usr/bin/ld: /tmp/cc91UyS4.o: in function `set_tag1':

rover.c:(.text+0x2976): undefined reference to `set_WORD_tag1'

collect2: error: ld returned 1 exit status

@jfiscus<https://github.com/jfiscus> kindly please give me the complete instructions along with command line arguments (with one example) for operating rover v0.1
OS - Ubuntu 20.04
compiler- gcc
