### ISSUE TITLE
How to generate .ctm and .stm files?

### ISSUE THREAD

**Issue by mukherjeesougata-eros** [usnistgov/SCTK#42]
How to generate .ctm and .stm files?

**Comment by mukherjeesougata-eros** [comment]
A gentle reminder for the same.

**Comment by jfiscus** [comment]
STM files are used for holding the reference transcript.  They are created by a human transcribing the speech. I typically convert the transcripts from highly detailed transcripts to STMs.  chfilt (in SCTK) is an example. 
CTM files are typically produced by a speech recognizer and each line represents a single word.
